### ISSUE TITLE
activities Slot: Synomye auf Values mappen

### ISSUE THREAD

**Issue by csacro** [csacro/Alexa-Skill-Emotionsadaptivitaet-im-Small-Talk#11]
@aai38 
Teste, das bitte mit dem Dot. Ich habe gelesen, dass das mappen von Synomymen auf Values in der Test-Simulation nicht geht, aber auf dem Dot funktioniert.
Wenn dus ausprobiert hast, bitte melde dich bitte (am besten so bald wie möglich). Falls es nicht geht muss ich mich nämlich darum kümmern.

**Comment by aai38** [comment]
Also hab ich getestet, hat aber nicht funktioniert. Sieht man in der Tabelle activities für arbeiten und gearbeitet ist ja beides jetzt in der Tabelle gespeichert.

**Comment by csacro** [comment]
Kannst du mal mit dem Dot schauen, ob Alexa dir bei den ActivitySolts nicht nur einen String, sondern mehrere Werte liefert (aktuell castest du da den Wert zu String). Habe nämlich dashier gefunden (und in der Test-Simulation bekomme ich nicht mehrere Werte, aber da soll es anscheinend ja sowieso nicht funktionieren):

Entity resolution
A process in which Alexa attempts to resolve the user's spoken utterance with possible slot values and synonyms for those slot values. You can define custom slot values with identfiers and synonyms. When the user's utterance resolves to match the slot value, your skill gets the canonical value defined for the entity, the actual value that the user spoke, and the unique identifier for that resolved value. See Define Synonyms and IDs for Slot Type Values (Entity Resolution): https://developer.amazon.com/de/docs/custom-skills/define-synonyms-and-ids-for-slot-type-values-entity-resolution.html

**Comment by aai38** [comment]
Habs jetzt hinbekommen und funktioniert auch soweit.
