### ISSUE TITLE
hallo.py: Zuweisung von 1,0,-1 und session.attributes

### ISSUE THREAD

**Issue by csacro** [csacro/Alexa-Skill-Emotionsadaptivitaet-im-Small-Talk#12]
@aai38 
überprüfe bitte nochmal, ob die Zuweisungen von 1, 0, -1  und session.attributes in den jeweiligen Fällen stimmen (hatte das Gefühl, dass teilweise wenig 0 dabei war)

@csacro 
@aai38 
testen und Fehler in der Zuweisung herausfinden

**Comment by aai38** [comment]
Also habs nochmal überprüft da haben halt paar 1 und -1 eins nicht gepasst, aber habs an der Alexa nochmal getestet und der Fehler kam jetzt gar nicht mehr, eventuell hast du den echt mit den switch cases gefixed.

**Comment by csacro** [comment]
zu "der Fehler kam jetzt gar nicht mehr":
Die switch cases haben da quasi nur ein "Pflaster" draufgeklebt: Der Code müsste immer noch wo den sessionkey falsch setzen, allerdings bekommt der User nichts davon mit, da es überall einen sinnvollen default-case gibt. Wenn du zum Testen überall im default-case die Alexa etwas "unpassendes" sagen lässt, dann bekommst du mit wenn in diesen Fall abgestiegen wurde

**Comment by aai38** [comment]
Also habs jetzt nochmal getestet, aber Alexa kommt tatsächlich nur in den default-case, wenn sie das auch soll. Du kannst das gerne auch nochmal probieren und mir Bescheid sagen, falls du nochmal einen Fehler findest. Bei mir gabs jetzt keinen mehr.

**Comment by csacro** [comment]
outdated
